[package]
name = "rust-mandelbrot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.23.14"
crossbeam = "0.8.1"
pixels = "0.5.0"
winit = "0.25.0"
winit_input_helper = "0.10"